# -*- coding: utf-8 -*-
"""
Created on 2022-02-25 00:26:14
---------
@summary:
---------
@author: Administrator
"""

from feapder import Item


class MedicalItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i medical.
    """

    __table_name__ = "medical"

    def __init__(self, *args, **kwargs):
        self.id = None  # 医疗机构编号
        self.address = None  # 医疗机构地址
        self.level = None  # 医疗机构等级
        self.name = None  # 医疗机构名称
        self.type = None  # 医疗机构类型
